name: Prerelease

on:
  push:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check if Prerelease is enabled
        id: is_pre_enabled
        uses: andstor/file-existence-action@v1
        with:
          files: '.changeset/pre.json'

      - name: Enter prerelease mode
        if: steps.is_pre_enabled.outputs.files_exists == 'false'
        run: pnpm changeset pre enter next

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
