name: Release Polaris for VS Code

on:
  push:
    tags:
      - 'vscode*' # Push events to matching vscode*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0

      - uses: actions/setup-node@v2
        name: Use Node.js 16.x
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm turbo run build --filter=polaris-for-vscode

      - name: Run Tests
        run: pnpm turbo run test --filter=polaris-for-vscode

      - name: Publish extension in the marketplace
        run: pnpm --filter=polaris-for-vscode exec vsce publish --no-dependencies
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
